export default {
  homeSidebar: [
    { type: 'autogenerated', dirName: 'Home' },
    { type: 'link', label: 'Proxmox', href: 'https://therepos.github.io/proxmox/' },
  ],
  certSidebar: [
    { type: 'autogenerated', dirName: 'Cert' },
  ],
};
