name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Sync theme.css from template
        run: |
          git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.PAT }}@github.com/therepos/docusaurus.git temp-docusaurus
          cd temp-docusaurus
          git sparse-checkout init --cone
          git sparse-checkout set src/css/theme.css
          git checkout main
          ls -l src/css/
          cp src/css/theme.css ../src/css/theme.css
          cd ..
          rm -rf temp-docusaurus

      - name: List pulled and copied files
        run: |
          ls -l temp-docusaurus/src/css/
          cp temp-docusaurus/src/css/theme.css src/css/theme.css
         
      - name: Build site
        run: npm run build

      - name: List build output
        run: ls -R ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
